### PR TITLE
disablie parsing to avoid breaking JSON contents

### PR DESCRIPTION
**Pull request by jakubgs**
Resolves: #53

I'd love to test this locally but I actually can't find how to install a locally built provider.

### CODE REVIEW

**Comment by toabi** [comment]
To locally test you have to create a funny directory structure like in https://learn.hashicorp.com/tutorials/terraform/provider-setup#test-the-provider - should contain `camptocamp/pass`

**Comment by jakubgs** [comment]
I've put it where it's supposed to be:
```
 > ls -l ~/.terraform.d/plugins/hashicorp.com/camptocamp/pass/2.0.0/linux_amd64/terraform-provider-pass
-rwxr-xr-x 1 sochan sochan 28640351 Apr 21 15:14 /home/sochan/.terraform.d/plugins/hashicorp.com/camptocamp/pass/2.0.0/linux_amd64/terraform-provider-pass
```
But when I try to use it Terraform says it's missing and I need to `terraform init`:
```
 > terraform plan

Error: Could not load plugin
...
```
But when I run `terraform init` it just installs the one from the repo:
```
 > terraform init
...
 > ls -l ./.terraform/providers/registry.terraform.io/camptocamp/pass/2.0.0/linux_amd64/terraform-provider-pass_v2.0.0 
-rwxrwxr-x 1 sochan sochan 20344832 Apr 21 15:15 ./.terraform/providers/registry.terraform.io/camptocamp/pass/2.0.0/linux_amd64/terraform-provider-pass_v2.0.0
```
And if I try to replace that binary with the one I built I get:
```
 > cp ~/.terraform.d/plugins/hashicorp.com/camptocamp/pass/2.0.0/linux_amd64/terraform-provider-pass ./.terraform/providers/registry.terraform.io/camptocamp/pass/2.0.0/linux_amd64/terraform-provider-pass_v2.0.0

 > terraform plan

Error: Could not load plugin
...
```
So I'm not sure how this is supposed to work.

**Comment by fredleger** [comment]
Pleeeeeeeeasssssseeeeeeee merge this one ;-)

Need it !

**Comment by jakubgs** [comment]
Would be nice, yeah.

**Comment by ErwinSteffens** [comment]
Any updates here?

**Comment by arthurk** [comment]
@raphink any updates? would be useful if this PR could get merged

**Comment by jakubgs** [comment]
Any updates?

**Comment by jakubgs** [comment]
Thank you.

**Pull request merged**
