### PR TITLE
add mutex to protect against concurrent operations

### PR DESCRIPTION
**Pull request by ElKiwos**
based on https://github.com/mtl-wgtwo/terraform-provider-pass/commit/8bc844ae013b20961212c0973d79e521d4bc8e79

### CODE REVIEW

**Comment by toabi** [comment]
Cool, I guess that would solve #20

**Comment by raphink** [comment]
It doesn't seem to solve #20 actually. I'm still getting the errors.

**Comment by toabi** [comment]
@raphink weird. what issues do you get?

For me it works with this version:

```
❯ terraform apply

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # pass_password.a will be created
  + resource "pass_password" "a" {
      + id       = (known after apply)
      + password = (sensitive value)
      + path     = "test/a"
    }

  # pass_password.b will be created
  + resource "pass_password" "b" {
      + id       = (known after apply)
      + password = (sensitive value)
      + path     = "test/b"
    }

  # pass_password.c will be created
  + resource "pass_password" "c" {
      + id       = (known after apply)
      + password = (sensitive value)
      + path     = "test/c"
    }

Plan: 3 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

pass_password.c: Creating...
pass_password.b: Creating...
pass_password.a: Creating...
pass_password.b: Creation complete after 3s [id=test/b]
pass_password.c: Creation complete after 5s [id=test/c]
pass_password.a: Creation complete after 7s [id=test/a]

Apply complete! Resources: 3 added, 0 changed, 0 destroyed.
```

And destruction:

```
❯ terraform destroy
pass_password.a: Refreshing state... [id=test/a]
pass_password.b: Refreshing state... [id=test/b]
pass_password.c: Refreshing state... [id=test/c]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  - destroy

Terraform will perform the following actions:

  # pass_password.a will be destroyed
  - resource "pass_password" "a" {
      - data     = (sensitive value)
      - id       = "test/a" -> null
      - password = (sensitive value)
      - path     = "test/a" -> null
    }

  # pass_password.b will be destroyed
  - resource "pass_password" "b" {
      - data     = (sensitive value)
      - id       = "test/b" -> null
      - password = (sensitive value)
      - path     = "test/b" -> null
    }

  # pass_password.c will be destroyed
  - resource "pass_password" "c" {
      - data     = (sensitive value)
      - id       = "test/c" -> null
      - password = (sensitive value)
      - path     = "test/c" -> null
    }

Plan: 0 to add, 0 to change, 3 to destroy.

Do you really want to destroy all resources?
  Terraform will destroy all your managed infrastructure, as shown above.
  There is no undo. Only 'yes' will be accepted to confirm.

  Enter a value: yes

pass_password.c: Destroying... [id=test/c]
pass_password.b: Destroying... [id=test/b]
pass_password.a: Destroying... [id=test/a]
pass_password.c: Destruction complete after 2s
pass_password.b: Destruction complete after 4s
pass_password.a: Destruction complete after 6s

Destroy complete! Resources: 3 destroyed.
```

**Comment by raphink** [comment]
OK. It must be another issue on my side then.

**Comment by raphink** [comment]
My bad, I had several versions of the plugins in different paths...

**Pull request merged**
